dist: trusty
language: d
d:
  - dmd
  - ldc

before_script: git fetch --unshallow
script:
  - "dub --config=test"

os:
  - linux
  - osx

matrix:
  include:
    - d: dmd-beta
      os: linux
    - d: dmd-nightly
      os: linux
    - d: ldc-beta
      os: linux
