platform:
  - x64
  - x86

configuration:
  - LLVM 10.0.0
  - LLVM 9.0.0
  - LLVM 8.0.0
  - LLVM 6.0.0

environment:
  DVersion: stable

  matrix:
    - d: dmd
    - d: ldc

init:
  - ps: $env:LLVM_VERSION = $env:CONFIGURATION.split(" ")[1]
  - ps: |
      $env:arch = if ($env:PLATFORM -eq 'x86')
      {
        if ($env:d -eq 'dmd') { 'x86_mscoff' } else { 'x86' }
      }
      else
      {
        'x86_64'
      }

install:
  - ps: tools/install_dc.ps1
  - ps: dub tools/download_llvm.d --arch=$env:arch
  - cp tmp/clang/bin/libclang.dll .
  - cp tmp/clang/bin/libclang.dll tests/functional/test_package

build_script:
  - echo dummy build script - dont remove me

before_test:
  - echo dummy test script - dont remove me

test_script:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq 'true')
      {
        tools/build_release.ps1
      }
      else
      {
        dub test --verror --arch=$env:arch --compiler=$env:DC
      }

artifacts:
  - path: dstep*.7z

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: 75htvSwus8XM6rUYfMqHMyEzHfqd8vmVjZ3bhg8OyFf2kGlMEFt5GmLVa3Pc9hhu
  artifact: /dstep.+\.7z/
  draft: true
  on:
    appveyor_repo_tag: true
    configuration: LLVM 10.0.0
    d: ldc
